// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// API which provides support for ChromeOS Accessibility features in the
// browser.

[Namespace=(chrome, accessibilityServicePrivate), platforms=("chromeos", "lacros")]
callback VoidCallback = void();

[Namespace=(chrome, accessibilityServicePrivate), platforms=("chromeos", "lacros")]
interface Functions {
  // Called when Select to Speak in ChromeOS should speak the current
  // text selection; fired when the context menu option was clicked in
  // a selection context.
  [supportsPromises] static void speakSelectedText(
    optional VoidCallback callback);
};
